# Generated by Django 3.2.9 on 2021-11-28 11:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_auto_20211123_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='blaundry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 11, 28, 11, 5, 52, 75457, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='glaundry',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
