# Generated by Django 3.2.5 on 2021-11-14 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('laundry_id', models.AutoField(help_text='Unique laundry num. for student table', primary_key=True, serialize=False)),
                ('college_id', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=200)),
                ('mobile_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('room_num', models.CharField(max_length=10)),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.gender')),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hostel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
    ]
