# Generated by Django 3.2.9 on 2021-11-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_employeeprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='hostels',
            new_name='hostel',
        ),
    ]
