# Generated by Django 3.2.9 on 2021-11-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_gender_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(choices=[('', 'Choose'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.CharField(choices=[('', 'Choose'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
