# Generated by Django 3.2.9 on 2021-11-28 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20211128_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gender'),
        ),
    ]
